baseURL = 'https://thegoldenkey.netlify.app/'
languageCode = 'en-us'
title = 'The Golden Key🔑'
theme = "hugo-theme-relearn"

[outputs]
  home = ["HTML", "RSS", "PRINT", "SEARCH", "SEARCHPAGE"]
  section = ["HTML", "RSS", "PRINT"]
  page = ["HTML", "RSS", "PRINT"]

[params]
themeVariant = [ "gold-theme", "auto", "relearn-bright", "relearn-light", "relearn-dark", "learn", "neon", "blue", "green", "red" ]

themeVariantAuto = [ "relearn-light", "relearn-dark" ]
