baseURL = 'https://thegoldenkey.netlify.app/'
languageCode = 'en-us'
title = 'The Golden Key🔑'
theme = "hugo-theme-relearn"

[outputs]
  home = ["HTML", "RSS", "PRINT", "SEARCH", "SEARCHPAGE"]
  section = ["HTML", "RSS", "PRINT"]
  page = ["HTML", "RSS", "PRINT"]

[params]
  # Change default color scheme with a variant one.
themeVariant = [ "auto", "relearn-bright", "relearn-light", "relearn-dark", "learn", "gold-theme" ,"neon", "blue", "green", "red" ]

themeVariantAuto = [ "relearn-light", "relearn-dark" ]

